import { Product } from '@/types/Product.type';

export const PRODUCT_LIST: Product[] = [
  {
    name: 'product.pinkman.name',
    carouselImage: '/onyx-pinkman.png',
    largeImage: '/onyx-pinkman.png',
    description: 'product.pinkman.description',
    tasteDescription: 'product.pinkman.tasteDescription',
    active: true,
  },
  {
    name: 'product.supernova.name',
    carouselImage: '/onyx-supernova.png',
    largeImage: '/onyx-supernova.png',
    description: 'product.supernova.description',
    tasteDescription: 'product.supernova.tasteDescription',
  },
  {
    name: 'product.banana.name',
    carouselImage: '/onyx-banana.png',
    largeImage: '/onyx-banana.png',
    description: 'product.banana.description',
    tasteDescription: 'product.banana.tasteDescription',
  },
  {
    name: 'product.energy.name',
    carouselImage: '/onyx-energy.png',
    largeImage: '/onyx-energy.png',
    description: 'product.energy.description',
    tasteDescription: 'product.energy.tasteDescription',
  },
  {
    name: 'product.kiwi.name',
    carouselImage: '/onyx-kiwi.png',
    largeImage: '/onyx-kiwi.png',
    description: 'product.kiwi.description',
    tasteDescription: 'product.kiwi.tasteDescription',
  },
  {
    name: 'product.lemongrass.name',
    carouselImage: '/onyx-lemongrass.png',
    largeImage: '/onyx-lemongrass.png',
    description: 'product.lemongrass.description',
    tasteDescription: 'product.lemongrass.tasteDescription',
  },
  {
    name: 'product.strawberry.name',
    carouselImage: '/onyx-strawberry.png',
    largeImage: '/onyx-strawberry.png',
    description: 'product.strawberry.description',
    tasteDescription: 'product.strawberry.tasteDescription',
  },
  {
    name: 'product.lemon.name',
    carouselImage: '/onyx-lemon.png',
    largeImage: '/onyx-lemon.png',
    description: 'product.lemon.description',
    tasteDescription: 'product.lemon.tasteDescription',
  },
  {
    name: 'product.peach.name',
    carouselImage: '/onyx-peach.png',
    largeImage: '/onyx-peach.png',
    description: 'product.peach.description',
    tasteDescription: 'product.peach.tasteDescription',
  },
  {
    name: 'product.pineapple.name',
    carouselImage: '/onyx-pineapple.png',
    largeImage: '/onyx-pineapple.png',
    description: 'product.pineapple.description',
    tasteDescription: 'product.pineapple.tasteDescription',
  },
  {
    name: 'product.mango.name',
    carouselImage: '/onyx-mango_yoghurt.png',
    largeImage: '/onyx-mango_yoghurt.png',
    description: 'product.mango.description',
    tasteDescription: 'product.mango.tasteDescription',
  },
  {
    name: 'product.grape.name',
    carouselImage: '/onyx-grape.png',
    largeImage: '/onyx-grape.png',
    description: 'product.grape.description',
    tasteDescription: 'product.grape.tasteDescription',
  },
  {
    name: 'product.wild.name',
    carouselImage: '/onyx-wild_strawberry.png',
    largeImage: '/onyx-wild_strawberry.png',
    description: 'product.wild.description',
    tasteDescription: 'product.wild.tasteDescription',
  },
];
