import { Product } from '@/types/Product.type';

export const PRODUCT_LIST: Product[] = [
  {
    name: 'product.pinkman.name',
    carouselImage: '/PINKMAN.png',
    largeImage: '/PINKMAN.png',
    description: 'product.pinkman.description',
    tasteDescription: 'product.pinkman.tasteDescription',
    active: true,
  },
  {
    name: 'product.supernova.name',
    carouselImage: '/SUPERNOVA.png',
    largeImage: '/SUPERNOVA.png',
    description: 'product.supernova.description',
    tasteDescription: 'product.supernova.tasteDescription',
  },
  {
    name: 'product.banana.name',
    carouselImage: '/BANANA.png',
    largeImage: '/BANANA.png',
    description: 'product.banana.description',
    tasteDescription: 'product.banana.tasteDescription',
  },
  {
    name: 'product.energy.name',
    carouselImage: '/ENERGY.png',
    largeImage: '/ENERGY.png',
    description: 'product.energy.description',
    tasteDescription: 'product.energy.tasteDescription',
  },
  {
    name: 'product.kiwi.name',
    carouselImage: '/KIWI.png',
    largeImage: '/KIWI.png',
    description: 'product.kiwi.description',
    tasteDescription: 'product.kiwi.tasteDescription',
  },
  {
    name: 'product.lemongrass.name',
    carouselImage: '/LEMONGRASS.png',
    largeImage: '/LEMONGRASS.png',
    description: 'product.lemongrass.description',
    tasteDescription: 'product.lemongrass.tasteDescription',
  },
  {
    name: 'product.strawberry.name',
    carouselImage: '/STRAWBERRY.png',
    largeImage: '/STRAWBERRY.png',
    description: 'product.strawberry.description',
    tasteDescription: 'product.strawberry.tasteDescription',
  },
  {
    name: 'product.lemon.name',
    carouselImage: '/LEMON.png',
    largeImage: '/LEMON.png',
    description: 'product.lemon.description',
    tasteDescription: 'product.lemon.tasteDescription',
  },
  {
    name: 'product.peach.name',
    carouselImage: '/PEACH.png',
    largeImage: '/PEACH.png',
    description: 'product.peach.description',
    tasteDescription: 'product.peach.tasteDescription',
  },
  {
    name: 'product.pineapple.name',
    carouselImage: '/PINEAPPLE.png',
    largeImage: '/PINEAPPLE.png',
    description: 'product.pineapple.description',
    tasteDescription: 'product.pineapple.tasteDescription',
  },
  {
    name: 'product.mango.name',
    carouselImage: '/MANGO-YOG.png',
    largeImage: '/MANGO-YOG.png',
    description: 'product.mango.description',
    tasteDescription: 'product.mango.tasteDescription',
  },
  {
    name: 'product.grape.name',
    carouselImage: '/GPAPE.png',
    largeImage: '/GPAPE.png',
    description: 'product.grape.description',
    tasteDescription: 'product.grape.tasteDescription',
  },
  {
    name: 'product.wild.name',
    carouselImage: '/WILDSTRAWBERRY.png',
    largeImage: '/WILDSTRAWBERRY.png',
    description: 'product.wild.description',
    tasteDescription: 'product.wild.tasteDescription',
  },
];
